GET http://localhost:3000/api HTTP/1.1
###
GET http://localhost:3000/api/fruits HTTP/1.1
###
GET https://localhost:3000/api HTTP/1.1
###
POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json

{
    "id": "4",
    "name": "Pear"
}
